apiVersion: v1
kind: ConfigMap
metadata:
  name: config-for-database
  namespace: exercises
data:
  initialize.sql: |
    CREATE TABLE pongs (pong VARCHAR(50));
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-for-database-env
  namespace: exercises
data:
  hostPgsql: pingpong-database-service
  portPgsql: "5432"
  userPgsql: postgres
  passwordPgsql: postgres
  dbPgsql: pingpong
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-for-app-env
  namespace: exercises
data:
  applicationport: "3000"