apiVersion: v1
kind: Service
metadata:
  name: pingpong-database-service
  namespace: exercises
spec:
  ports:
    - port: 5432
      name: postgres-port
  clusterIP: None
  selector:
    app: pingpong-database