apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: imagesvolume
          persistentVolumeClaim:
            claimName: imagesclaim
      containers:
        - name: todoapp
          image: vilkorppi/todoapp:v2.2
          volumeMounts:
          - name: imagesvolume
            mountPath: /usr/src/app/images