apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagesclaim
  namespace: project
spec:
  storageClassName: imagespv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi