apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: vilkorppi/pingpong:v2.7
          env:
            - name: dbhost
              valueFrom:
                configMapKeyRef:
                    name: config-for-database-env
                    key: hostPgsql
            - name: dbport
              valueFrom:
                configMapKeyRef:
                    name: config-for-database-env
                    key: portPgsql
            - name: dbname
              valueFrom:
                configMapKeyRef:
                    name: config-for-database-env
                    key: dbPgsql
            - name: dbusername
              valueFrom:
                configMapKeyRef:
                    name: config-for-database-env
                    key: userPgsql
            - name: dbpassword
              valueFrom:
                configMapKeyRef:
                    name: config-for-database-env
                    key: passwordPgsql
            - name: port
              valueFrom:
                configMapKeyRef:
                    name: config-for-app-env
                    key: applicationport